### ISSUE TITLE
El sitio web no funciona

### ISSUE THREAD

**Issue by SuperGamer18** [pipetboy2001/RetroArchivement-Download-games#1]
Hola, quiero reportar un problema con la versión web de este programa. Cada vez que trato de accederlo me da un error 500: "INTERNAL_SERVER_ERROR".
**This serverless function has crashed.** ¿Podrías por favor solucionar este problema?

**Comment by Scorpion16** [comment]
You download zip on project ant you are a index.html file, but if you make a search this page do not download (because archive.org). I testing a download in add a .env file

**Comment by pipetboy2001** [comment]
He solucionado el problema del error 500 que ocurría al acceder al sitio. 
El problema estaba relacionado con la falta del archivo .env, que contenía las variables de entorno necesarias. Después de agregar y configurar el archivo .env, el sitio ahora funciona correctamente.

Gracias por la ayuda y el reporte. ¡El problema está resuelto!
